### Test

GET http://localhost:5000/

### Users

### Register an user and sign in

POST http://localhost:5000/api/users/register
Content-Type: application/json

{
	"name": "Hugo",
	"email": "hugocal@teste.com",
	"password": "987654",
	"confirmPassword": "987654"
}

### Sign user in

POST http://localhost:5000/api/users/login
Content-Type: application/json

{
	"email": "jao7@teste.com",
	"password": "123123"
}

### Profile - OBS: Em Authorization favor inserir Bearer na frente do seu token

GET http://localhost:5000/api/users/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZDdiM2ViOTBiMTM1YzBhMWE3NWEzNCIsImlhdCI6MTc3NTgyNzE2OSwiZXhwIjoxNzc2NDMxOTY5fQ.kMFVFLMnjGaTmAaeTL6aXVvsjIepHaK_iSrJ-H62E8A

###
